# Generated by Django 4.1.5 on 2023-01-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(upload_to='', verbose_name='photo de profil')),
                ('username', models.CharField(max_length=128, verbose_name='nom')),
                ('interet', models.CharField(choices=[('SCIENCE', 'SCIENCES'), ('FILM', 'FILM'), ('STYLE', 'Mode de Style'), ('MUSIC', 'MUSIC'), ('SANTE', 'SANTE'), ('ECONOMIE', 'ECONOMIE'), ('SPORT', 'SPORT'), ('POLITIQUE', 'POLITIQUE'), ('DIVERTISSEMENT', 'DIVERTISSEMENT')], max_length=30, verbose_name='rôle')),
                ('biographie', models.TextField(max_length=1024, verbose_name='Biographie')),
            ],
        ),
    ]
